### ISSUE TITLE
No visualize.py in the code

### ISSUE THREAD

**Issue by pei0400** [atb033/multi_agent_path_planning#1]
Hi,
I like your code. But when I try to check the cbs result, "python3 ../visualize.py input.yaml output.yaml" does not work since there is no visualize.py file in the code. Could you please upload it?
Regards,
Peter

**Comment by atb033** [comment]
Hi Peter,

That file is already there in the repo ([file](https://github.com/atb033/multi_agent_path_planning/blob/master/centralized/visualize.py))

Are you sure that you ran the command in [this](https://github.com/atb033/multi_agent_path_planning/tree/master/centralized/cbs) folder

**Comment by pei0400** [comment]
Thanks, I got the file and run it. It is a pretty interesting program.
