### ISSUE TITLE
Saving to video currently does not work for lack of a canvas

### ISSUE THREAD

**Issue by notger** [atb033/multi_agent_path_planning#10]
See title.

You need to define a canvas before you define the function-animation.
I have some fixed and slightly cleaned up code, so if you invite me to the repo, I can push a PR, if you want.

Way to replicate issue: Try creating video output. You will get an error message that says that an object related to canvas is None and does not have a certain property.

**Comment by atb033** [comment]
You don't need to be a member of the repo to make a PR.

Can you please make fork the repo and then make a PR from that fork? Please check [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) out in case you aren't familiar with that work-flow

**Comment by notger** [comment]
Thanks, so far never worked with forks, PR only. Will do.

**Comment by notger** [comment]
Here we go: https://github.com/atb033/multi_agent_path_planning/pull/11 .

**Comment by atb033** [comment]
closing as the issue was not reproduced
