### ISSUE TITLE
Why is a preexisting output.yaml required?

### ISSUE THREAD

**Issue by snoyes** [atb033/multi_agent_path_planning#12]
https://github.com/atb033/multi_agent_path_planning/blob/9b273bbf9187e647a5e1e131ecb36d201cdd4c30/centralized/cbs/cbs.py#L337-L342

This code requires than a valid output yaml file already exists. I think it ought to gracefully handle the case that no such file exists.

**Comment by atb033** [comment]
Thanks for the suggestion. I do agree that it should exit gracefully. Would you like to open a PR for this?
