### ISSUE TITLE
KeyError while generating  multi-agent prioritized planning

### ISSUE THREAD

**Issue by deepak80** [atb033/multi_agent_path_planning#4]
I don't actually it's an issue or not. But I think there is a problem while generating planning/schedule for 8x8 or 32x32 grid.

I've only a little bit of knowledge about python.
![KeyError](https://user-images.githubusercontent.com/47783824/102223083-41bc1480-3f0a-11eb-9a66-7c76fc8a7c80.PNG)

**Comment by deepak80** [comment]
At least you've to see it once. Please help me out.

**Comment by deepak80** [comment]
There is no such key as dynamic_obstackles in all the ".yaml" files inside multi_agent_path_planning-master\centralized\benchmark\8x8_obst12 and multi_agent_path_planning-master\centralized\benchmark\32x32_obst12

Please help me out to visualize the result for 32x32 and 8x8 on VS code.

Operating System: Windows 10

**Comment by atb033** [comment]
It looks like an error that occurred since you haven't configured your environment properly. Can you tell me the command you used to run this code?

**Comment by deepak80** [comment]
Thank you for your quick response, Mr. Ashwin Bose.

I think you want to know python which interpreter??

so I was used python.exe on windows 10 which is the latest version of Python 3.

Now, I'm able to resolve the problem and able to correctly produce the outputs for 8x8 and 32x32.

The mistake that I've done that time is: 
--------------------------------------------

I'm running multi_sipp.py for .yaml's files that are located inside 8x8_obst12 & 32x32_obst204. instead, that would be cbs.py.
------------------------------------------------------------------------------------------------------------------------------------------


Suggestions that might be considered:

       1.) In addition numpy, matplotlib & scipy in requirements.txt there should be one more module should be added
            which is ffmpeg.
       2.) After running (pip3 install -r riquirements.txt) we've to download FFmpeg from the Internet and need to set it into the Path environment variable(Absolute path up to bin folder).


I tested on both Windows 10 & Ubuntu 20.04 LTS without having an FFmpeg module while generating video files with extension .mp4, .avi, etc. It's giving FFmpegWriterError(something like this) exception.

Without FFmpeg, I'm only able to generate .gif, .png, etc. Not any video file.

You've to at least test in your system if you don't believe in me and based on your observation add some more notes on the markdown file.

So that further, no one having issues while generating video file.

**Comment by deepak80** [comment]
I'm sure that is one issue related to Video file generation. You should correct it.

Once again I'm extremely thankful to you for your quick response.

This project is awesome.

**Comment by atb033** [comment]
Okay. I'll `ffmpeg` to the dependencies. Thanks for pointing it out :)

**Comment by paopao-16** [comment]
I've only a little bit of knowledge about python.
What should I do to fix this?
usage: multi_sipp.py [-h] map output
multi_sipp.py: error: the following arguments are required: map, output

WIN 11，python3.12
